#!/bin/bash
echo ""
echo -e "\033[1;31m Definir Data/Hora. \033[0m"
echo ""
echo -e "\033[1;31m Selecionar AMERICA e depois SAO PAULO. \033[0m"
echo ""
tput setaf 3 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
dpkg-reconfigure tzdata
apt-get update && apt-get upgrade
apt-get install unzip
wget 164.132.22.54/scripts_27/scripts.zip
unzip scripts.zip
chmod 755 AlterarSenha.sh
chmod 755 configvps.sh
chmod 755 ExcluirUsuario.sh
chmod 755 inst
chmod 755 NovoUsuarioSSH.sh
chmod 755 Online.sh
chmod 755 online_painel.sh
chmod 755 UsersOnline.sh
chmod 755 ValidarUsuarioSSH.sh
chmod 755 sshmanager.sh
./sshmanager.sh
rm sshmanager.sh scripts.zip
apt-get install python
wget https://raw.githubusercontent.com/andersonkroz/Meus-reposit-rio/master/userbackup.sh
